# Generated by Django 5.0.3 on 2024-03-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'verbose_name_plural': 'Contracts'},
        ),
    ]
