# Generated by Django 5.0.3 on 2024-03-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'ads'},
        ),
    ]
