# Generated by Django 5.0.3 on 2024-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('Оператор', 'Оператор'), ('Маркетолог', 'Маркетолог'), ('Менеджер', 'Менеджер')], max_length=50),
        ),
    ]
