# Generated by Django 5.0.3 on 2024-03-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_alter_contracts_options'),
        ('leads', '0002_alter_leads_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
    ]
